// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlKDcP70zrOmaxvZtiqJUIfJXSXGh0ufE',
    appId: '1:918030294442:web:bf42ef4645ce221c8fdfd3',
    messagingSenderId: '918030294442',
    projectId: 'todolist-2010',
    authDomain: 'todolist-2010.firebaseapp.com',
    storageBucket: 'todolist-2010.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5VNGx3y1IcRr8hWgnJX_1TNrKCDnP1cw',
    appId: '1:918030294442:android:cb187690ad40f3758fdfd3',
    messagingSenderId: '918030294442',
    projectId: 'todolist-2010',
    storageBucket: 'todolist-2010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPA4iE0HQJlKvqXudETNXLB7agB5KY8KM',
    appId: '1:918030294442:ios:f1363bb5999e3ced8fdfd3',
    messagingSenderId: '918030294442',
    projectId: 'todolist-2010',
    storageBucket: 'todolist-2010.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPA4iE0HQJlKvqXudETNXLB7agB5KY8KM',
    appId: '1:918030294442:ios:21254cfdc43984828fdfd3',
    messagingSenderId: '918030294442',
    projectId: 'todolist-2010',
    storageBucket: 'todolist-2010.appspot.com',
    iosBundleId: 'com.example.todoList.RunnerTests',
  );
}
